### ISSUE TITLE
Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4

### ISSUE THREAD

**Issue by matthewsuan** [jjgrainger/PostTypes#20]
On PostType Class and Taxonomy Class, I got this error:

`Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4`

Any thoughts?

Ty

**Comment by jjgrainger** [comment]
Hi @matthewsuan 

I've not come across this before,

could you provide me with an example of your code when this came up? Is that the full error message, or was there more?

Thanks,

Joe

**Comment by jjgrainger** [comment]
I believe I've worked out what the issue is reading this [StackOverflow answer](https://stackoverflow.com/questions/8971261/php-5-4-call-time-pass-by-reference-easy-fix-available#8971301).

Both the `Taxonomy` and `PostType` `register()` methods use `&$this` to pass the class by reference, which is now deprecated since PHP 5.3.

Should be simple to resolve by replacing instances of `&$this` to `$this`.

**Comment by matthewsuan** [comment]
thanks. I did re-installed composer and all went well.
