### ISSUE TITLE
taxonomy filter count incorrect when taxonomy is shared

### ISSUE THREAD

**Issue by eballeste** [jjgrainger/PostTypes#23]
The total of the filter amount does not filter by custom post type. For example, I am getting 7 total for the healthcare taxonomy when, for the current edit screen, it should be showing 3.
<img width="1100" alt="screen shot 2018-04-30 at 3 45 55 pm" src="https://user-images.githubusercontent.com/6924108/39447146-e18f5f24-4c8e-11e8-97e5-29984af2d292.png">

**Comment by jjgrainger** [comment]
Hi @eballeste 

This will be down to a recent change with the drop-down. Rather than creating a custom dropdown from a terms array, it's now using [`wp_dropdown_categories`](https://codex.wordpress.org/Function_Reference/wp_dropdown_categories) which will display a count for all post types, not for the current one.

After a bit of research it looks like it would need another filter to set the post type for that query, or look for alternative function to create the drop-down.

Thanks for bringing it up, I'll see about getting it fixed. :)

**Comment by jjgrainger** [comment]
Related to #66

**Comment by jjgrainger** [comment]
This was resolved in #81  by removing the term count from the dropdown list to match how WordPress core creates dropdown filters.
