### ISSUE TITLE
Feature request: use Extended CPTs library

### ISSUE THREAD

**Issue by abuyoyo** [jjgrainger/PostTypes#60]
Feature request: Would you consider using John Blackbourn's [Extended CPTs](https://github.com/johnbillion/extended-cpts) library as the core for your PostTypes library? Perhaps in your next major release.

The main appeal of using PostTypes is the ease-of-use and weak coupling with the WordPress hooks/filters system. Just write `new PostType('new_post_type')` in the global scope and the library takes care of the rest. It allows working with WordPress post types in a more object oriented/abstract fashion.
.
Extended CPT's still requires users of the library to hook into WordPress themselves, however the integration/edge-case handling is more robust than how `jjgrainger/PostTypes` handles things at the moment. The author is a WordPress core maintainer so his Extended library is very stable.

I think `PostTypes` (and the related interfaces - `Columns`, etc.) can be easily converted to wrapper classes for Extended-CPTs (or even as extension classes - tho that might be a bit tougher to maintain properly). The API can remain unchanged to a large degree.

**Comment by jjgrainger** [comment]
Thanks for the feature request, but unfortunately I'm against the idea of extending this library from another.

This will add an additional dependency to the project and another code base that people will need to familiarise themselves with in order to contribute.

For those reasons I am closing this issue out.

Thanks again :)
